import os
import random

import numpy as np
import torch
import torch.nn.functional as F
from peft import PeftModel
from torch.optim import Adam
from transformers import AutoModelForCausalLM, AutoTokenizer
from config.logger_config import sars_logger as logger


def compute_loss(logits, labels, prompt_len, advantage):
    """
    Computes the critic-free REINFORCE++ policy gradient loss for the exact tokens generated by a specific agent.
    """
    shift_logits = logits[0, prompt_len - 1: -1, :]
    shift_labels = labels[0, prompt_len:]

    log_probs = F.log_softmax(shift_logits, dim=-1)
    token_log_prob = log_probs[torch.arange(shift_labels.size(0)), shift_labels]
    return -token_log_prob.mean() * advantage

def compute_advantage(value, baseline_pool):
    if len(baseline_pool) < 2 or np.std(baseline_pool) == 0:
        return value - np.mean(baseline_pool)
    return (value - np.mean(baseline_pool)) / (np.std(baseline_pool) + 1e-8)

def optimize_adapters(backbone, lora_name, trajectories, epochs = 4):
    if not trajectories:
        return
    backbone.set_active_adapter(lora_name)
    model = backbone.model
    tokenizer = backbone.tokenizer
    model.train()

    trainable_params = filter(lambda p: p.requires_grad, model.parameters())
    optimizer = Adam(trainable_params, lr=2e-6)

    logger.info(f" -> Running {epochs} optimization epochs directly on unified memory for {lora_name}")

    for epoch in range(epochs):
        random.shuffle(trajectories)
        for traj in trajectories:
            optimizer.zero_grad()

            full_sequence = traj["prompt"] + traj["generation"]
            inputs = tokenizer(full_sequence, return_tensors="pt").to(model.device)
            prompt_len = tokenizer(traj["prompt"], return_tensors="pt")["input_ids"].shape[1]

            logits = model(**inputs).logits
            loss = compute_loss(logits, inputs["input_ids"], prompt_len, traj["advantage"])
            loss.backward()
            optimizer.step()

    # Auto-serialize parameters right back to the designated local storage path
    save_path = f"./adapters/{lora_name}_lora"
    os.makedirs(save_path, exist_ok=True)
    model.save_pretrained(save_path)
    logger.info(f" -> Synchronized and saved {lora_name} updates to disk.")