import torch
import torch.nn.functional as F

def compute_reinforce_pp_loss(logits, labels, prompt_len, advantage):
    """
    Computes the critic-free REINFORCE++ policy gradient loss
    for the exact tokens generated by a specific agent.
    """
    shift_logits = logits[0, prompt_len - 1: -1, :]
    shift_labels = labels[0, prompt_len:]

    log_probs = F.log_softmax(shift_logits, dim=-1)
    token_log_prob = log_probs[torch.arange(shift_labels.size(0)), shift_labels]


    return -token_log_prob.mean() * advantage